version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - run:
          name: Run all tests
          command: cargo test --all
